SevenManagerBundle\Document\Pages\Homepage:
    #uri_schema:/{locale}/seven-manager/homepage/{date}/{title}
    uri_schema: /{locale}/seven-manager/homepage/{title}
    token_providers:
        #date: [content_datetime, { method: getDate }] // Call methods and add to variables used by uri_schema
        title: [content_method, { method: getTitle }]
        locale: [content_method, { method: getLocale }]

SevenManagerBundle\Document\Pages\Node:
    uri_schema: /{locale}/seven-manager/node/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Document\Pages\Page:
    uri_schema: /{locale}/seven-manager/page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Document\Pages\Post:
    uri_schema: /{locale}/seven-manager/post/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Document\Pages\Article:
    uri_schema: /{locale}/seven-manager/article/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Document\Pages\Gallery:
    uri_schema: /{locale}/seven-manager/gallery/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Document\Pages\Form:
    uri_schema: /{locale}/seven-manager/form/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

# Fixtures
SevenManagerBundle\Fixtures\Document\SimplePage:
    uri_schema: /seven-manager/fixtures/simple-page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManagerBundle\Fixtures\Document\SimplePost:
    uri_schema: /seven-manager/fixtures/simple-post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]