services:
    # Seven Manager - Initializer
    seven_manager.pages.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - Seven Manager - Initializer
            - ["/seven-manager", "/seven-manager/homepage", "/seven-manager/page", "/seven-manager/article", "/seven-manager/node", "/seven-manager/post", "/seven-manager/form", "/seven-manager/gallery", "/seven-manager/slideshow", "/seven-manager/images", ]
        tags:
            - { name: doctrine_phpcr.initializer }
    seven_manager.fixtures.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - Seven Manager - Fixtures Initializer
            - ["/seven-manager/fixtures/pages", "/seven-manager/fixtures/posts", "/seven-manager/fixtures/content", "/seven-manager/fixtures/routes", "/seven-manager/fixtures/type-a", "/seven-manager/fixtures/type-b", "/seven-manager/fixtures/type-c"]
        tags:
            - { name: doctrine_phpcr.initializer }

    # Seven Manager - Station Manager
    seven_manager.station_manager:
        class:  SevenManagerBundle\Manager\StationManager
            
    # Seven Manager - Call Content Bundle
    seven_manager.admin.pages.homepage:
        class: SevenManagerBundle\Admin\Pages\HomepageAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Homepage
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.homepage }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.node:
        class: SevenManagerBundle\Admin\Pages\NodeAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Node
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.node }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.page:
        class: SevenManagerBundle\Admin\Pages\PageAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.post:
        class: SevenManagerBundle\Admin\Pages\PostAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.post }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.article:
        class: SevenManagerBundle\Admin\Pages\ArticleAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Article
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.article }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.gallery:
        class: SevenManagerBundle\Admin\Pages\GalleryAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Gallery
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.gallery }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.pages.form:
        class: SevenManagerBundle\Admin\Pages\FormAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Pages\Form
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Pages', label: seven_manager.shared.labels.form }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
    seven_manager.admin.containers.slideshow:
        class: SevenManagerBundle\Admin\Containers\SlideshowAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Containers\Slideshow
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven manager - Containers', label: Slideshow }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]
            - [setSlideTypeOne, [seven_manager.admin.blocks.slideone]]
    seven_manager.admin.blocks.slideone:
        class: SevenManagerBundle\Admin\Blocks\SlideTypeOneAdmin
        arguments:
            - ''
            - SevenManagerBundle\Document\Blocks\SlideTypeOne
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven manager - Blocks', label: Slide Type One }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]